# Generated by Django 3.1.12 on 2026-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
