# Generated by Django 3.1.12 on 2026-02-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user_last_name_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship_back_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_front_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
